name = "BasesAndSamples"
uuid = "b47663c2-775e-4d88-bb56-6bef842cff7a"
authors = ["nanleij <38724800+nanleij@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
Combinatorics = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
